// This file is auto-generated by next-intl, do not edit directly.
// See: https://next-intl.dev/docs/workflows/typescript#messages-arguments

declare const messages: {
  "LocaleSwitcher": {
    "label": "Change language",
    "en": "English",
    "zh-TW": "Traditional Chinese",
    "locale": "{locale, select, en {English} zh-TW {Traditional Chinese}}"
  },
  "ShanChi": {
    "name": "ShanChi"
  }
};
export default messages;